name       : qt5-x11extras
version    : 5.13.0
release    : 15
source     :
    - https://download.qt.io/official_releases/qt/5.13/5.13.0/submodules/qtx11extras-everywhere-src-5.13.0.tar.xz : f33fe1cf2258bc972171f723c6f37208da47f578b09876fea47c7ba558a8f1d6
license    :
    - GFDL-1.3
    - GPL-2.0
    - GPL-3.0
    - LGPL-2.1
    - LGPL-3.0
component  : desktop.qt
summary    : Qt5 X11 Extra Components
description: |
    Qt X11 Extras enables the Qt programmer to write applications for the Linux/X11 platform. Applications developed with Qt can also be deployed across several other desktop and embedded operating systems without having to rewrite the source code.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
setup      : |
    %qmake qtx11extras.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
