name       : qt5-x11extras
version    : 5.9.0
release    : 2
source     :
    - http://download.qt.io/official_releases/qt/5.9/5.9.0/submodules//qtx11extras-opensource-src-5.9.0.tar.xz : 9e03d2856dc21eb59f2c8a572f33960a32f6f990b3353440d0e744fc93d0bf6a
license    :
    - GFDL-1.3
    - GPL-2.0
    - GPL-3.0
    - LGPL-2.1
    - LGPL-3.0
component  : desktop.qt
summary    : Qt5 X11 Extra Components
description: |
    Qt X11 Extras enables the Qt programmer to write applications for the Linux/X11 platform. Applications developed with Qt can also be deployed across several other desktop and embedded operating systems without having to rewrite the source code.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
setup      : |
    %qmake qtx11extras.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
