name       : qt5-x11extras
version    : 5.12.1
release    : 12
source     :
    - https://download.qt.io/official_releases/qt/5.12/5.12.1/submodules/qtx11extras-everywhere-src-5.12.1.tar.xz : 08fb1c40e1562d43087368a5efa39569fa1ad52b72d2360f9fc1fe18b00da366
license    :
    - GFDL-1.3
    - GPL-2.0
    - GPL-3.0
    - LGPL-2.1
    - LGPL-3.0
component  : desktop.qt
summary    : Qt5 X11 Extra Components
description: |
    Qt X11 Extras enables the Qt programmer to write applications for the Linux/X11 platform. Applications developed with Qt can also be deployed across several other desktop and embedded operating systems without having to rewrite the source code.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
setup      : |
    %qmake qtx11extras.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
